### ISSUE TITLE
New production URL?

### ISSUE THREAD

**Issue by ctownsen357** [usnistgov/Community-Resilience#1]
What will be the new production URL for the CRPanel.org website? I'm going to write an Ansible deployment script and want to add a step to configure the WordPress database value for the URL of the new site.  If this isn't done it won't serve up pages correctly.

**Comment by BTD2** [comment]
We are in the process of establishing the URL now. I will get back to you soon with more information.

Thanks,
Benjamin Davis
Community Resilience Group
Materials and Structural Systems Division
Engineering Laboratory
National Institute of Standards and Technology
301-975-6071
Benjamin.Davis@NIST.govmailto:Benjamin.Davis@NIST.gov

**Comment by BTD2** [comment]
Chris,

I have confirmed that the production URL will be https://pages.nist.gov/Crpanelhttps://pages.nist.gov/CRpanel.

Thanks,
Benjamin Davis
Community Resilience Group
Materials and Structural Systems Division
Engineering Laboratory
National Institute of Standards and Technology
301-975-6071
Benjamin.Davis@NIST.govmailto:Benjamin.Davis@NIST.gov

**Comment by ctownsen357** [comment]
Great, thank you Benjamin.
