### ISSUE TITLE
Read/Write access

### ISSUE THREAD

**Issue by ctownsen357** [usnistgov/Community-Resilience#2]
May I have read/write access so that I may commit my changes to this repository?

**Comment by BTD2** [comment]
Give me a call to discuss 301-975-6071

**Comment by BTD2** [comment]
Hey Chris,

Per the NIST guidance I cannot grant you write access to the repository. Can you send a pull request instead?

Thanks,
Benjamin Davis
Community Resilience Group
Materials and Structural Systems Division
Engineering Laboratory
National Institute of Standards and Technology
301-975-6071
Benjamin.Davis@NIST.govmailto:Benjamin.Davis@NIST.gov

**Comment by ctownsen357** [comment]
Yes, of course.  I'll send it once it is ready.

**Comment by ctownsen357** [comment]
Would you have someone add something to the project? It doesn't allow me to fork because there is nothing in the repository.  My understanding of the Git work flow that you want me to use is:
- create a fork
- add my bits
- submit a pull request to be reviewed and approved by your team

Right now it won't let me fork the project because there is nothing in the repository.  If I'm mistaken about that work flow please let me know.

**Comment by BTD2** [comment]
Give me a call to discuss.

Benjamin Davis
Community Resilience Group
Materials and Structural Systems Division
Engineering Laboratory
National Institute of Standards and Technology
301-975-6071
Benjamin.Davis@NIST.govmailto:Benjamin.Davis@NIST.gov

**Comment by ctownsen357** [comment]
Thank you for the help Benjamin.
